name = "ForwardDiffSparseSolve"
uuid = "45cea28e-a2c2-48b5-bf61-da5c0d9b8d5d"
authors = ["Mark A SFF <mjagerton@ucdavis.edu> and contributors"]
version = "0.1.1"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
